#!/usr/bin/env bash
# goc go: compile every .c in a Go package and link it. One command.
# Product defaults are the QuickJS set (see scripts/goc-product-lib.sh).
# CGO_ENABLED=0 so the go command ignores the .c files and does not invoke
# the system C compiler. Bodies are packed through toolexec.
set -euo pipefail
SELF="$(cd "$(dirname "$0")" && pwd)"
ROOT="${GOC_ROOT:-$(cd "$SELF/.." && pwd)}"
export GOC_ROOT="$ROOT"
# shellcheck source=goc-flags.sh
source "$SELF/goc-flags.sh"
# shellcheck source=goc-product-lib.sh
source "$SELF/goc-product-lib.sh"
export GOTOOLCHAIN=local GOPROXY=off GOSUMDB=off CGO_ENABLED=0

usage() {
  cat <<'EOF'
usage: goc go [dir] [-o binary] [flags] [-- clang-args...]

dir is a Go package (default: .). Every *.c in that directory is compiled
and linked into the package. Inherited GOC_* variables are ignored.

  linux/amd64, CGO_ENABLED=0, internal linking. The C may not call libc.
  Writes goc_marker_amd64.s if the package has no assembly file, so Go
  accepts bodyless declarations. You still declare each C function in Go.
  Defaults: -O3 --default-ptr-color cptr --fast-stack-alloca
  --fast-stack-alloca is much faster and single-threaded only. The alloca
  pool cursor is process-global, so concurrent calls are not thread-safe.
  Morestack, splittable frames, and sptr maps are always on.

Package main produces a binary (default: <dir>/<dirname>). Any other package
is type-checked and packed into the build cache; -o is refused.
EOF
  echo
  goc_flags_help
}

# Flags are the interface. A variable left in the environment does not
# change this command.
goc_isolate_product_env

DIR="."
OUT=""
EXTRA=()
while [[ $# -gt 0 ]]; do
  if goc_consume_flag "$1" "${2:-}"; then
    shift "$GOC_FLAG_SHIFT"
    continue
  fi
  case "$1" in
    -h|--help) usage; exit 0 ;;
    -o) OUT="${2:?goc go: -o needs a path}"; shift 2 ;;
    --) shift; EXTRA=("$@"); break ;;
    -*) goc_die "unknown flag: $1 (clang arguments go after --)" ;;
    *) DIR="$1"; shift ;;
  esac
done

[[ -d "$DIR" ]] || goc_die "not a directory: $DIR"
DIR="$(cd "$DIR" && pwd)"
case "$(go env GOOS)/$(go env GOARCH)" in
  linux/amd64) ;;
  *) goc_die "goc go builds linux/amd64 only (got $(go env GOOS)/$(go env GOARCH))" ;;
esac
if [[ "${GOC_ARCH:-amd64}" != amd64 ]]; then
  goc_die "goc go builds linux/amd64 only (--arch ${GOC_ARCH})"
fi

goc_product_defaults
goc_require_tools

NAME="$(cd "$DIR" && go list -f '{{.Name}}' .)"
IMPORT="$(cd "$DIR" && go list -f '{{.ImportPath}}' .)"
if goc_flag_seen pkg; then
  PREFIX="$GOC_PKG"
else
  if [[ "$NAME" == "main" ]]; then
    PREFIX="main"
  else
    PREFIX="$IMPORT"
  fi
  export GOC_PKG="$PREFIX"
fi
export GOC_PACK_PKG="$PREFIX"
FWD=()
goc_append_resolved_flags FWD
echo "goc go: ${FWD[*]}" >&2

shopt -s nullglob
SRCS=( "$DIR"/*.c )
[[ ${#SRCS[@]} -gt 0 ]] || goc_die "no .c files in $DIR"
ASMS=( "$DIR"/*.s )
if [[ ${#ASMS[@]} -eq 0 ]]; then
  cat >"$DIR/goc_marker_amd64.s" <<'EOF'
// Code generated by goc go. Do not edit.
// Present so Go accepts bodyless declarations of the C functions.
// The function bodies are the packed goc goobj, not this TEXT.
#include "textflag.h"

TEXT ·gocMarker(SB), NOSPLIT|NOFRAME, $0-0
	RET
EOF
  echo "goc go: wrote $DIR/goc_marker_amd64.s" >&2
fi

CACHE="$ROOT/build/goc-go/$(printf '%s' "$DIR" | sha256sum | awk '{print $1}' | cut -c1-16)"
mkdir -p "$CACHE"
BINOBJ=""
for src in "${SRCS[@]}"; do
  base="$(basename "$src" .c)"
  obj="$CACHE/$base.o"
  echo "goc go: compile $src" >&2
  "$ROOT/cmd/goc" build "$src" -o "$obj" --all --goabi "${FWD[@]}" "${EXTRA[@]}"
  BINOBJ="${BINOBJ:+$BINOBJ }$obj"
done
export GOC_BINOBJ="$BINOBJ"

if [[ "$NAME" == "main" ]]; then
  if [[ -z "$OUT" ]]; then
    OUT="$DIR/$(basename "$DIR")"
  elif [[ "$OUT" != /* ]]; then
    OUT="$(pwd)/$OUT"
  fi
  mkdir -p "$(dirname "$OUT")"
else
  if [[ -n "$OUT" ]]; then
    goc_die "-o is for package main; $IMPORT is package $NAME"
  fi
fi

(
  cd "$DIR"
  export CGO_ENABLED=0 GOFLAGS= GOTOOLCHAIN=local GOPROXY=off GOSUMDB=off
  if [[ "$NAME" == "main" ]]; then
    go build -a -toolexec "$ROOT/backend/tools/toolexec_pack_goobj.sh" -o "$OUT" .
  else
    go build -a -toolexec "$ROOT/backend/tools/toolexec_pack_goobj.sh" .
  fi
)
if [[ "$NAME" == "main" ]]; then
  echo "goc go: $OUT"
else
  echo "goc go: packed $IMPORT"
fi
